# Playbook to Install PowerShell & Dependencies on CentOS
---
- name: Install PowerShell & Deps to CentOS
  hosts: localhost
  vars_files:
    - vars/software
    
  tasks:

  - name: install packages    
    yum:
      with_items: "{{ powershell_pkg }}"
      state: latest
...
